cmd/plakar/plakar.go, network/types.go, snapshot/push.go, snapshot/snapshot.go, snapshot/snapshot_types.go, storage/client/client.go, storage/client/client_types.go, storage/database/database.go, storage/database/database_types.go, storage/fs/fs_store.go, storage/fs/fs_types.go, storage/storage.go, storage/storage_types.go
=> Issue6 reverse indexes

cmd/plakar/cmd_cat.go, cmd/plakar/cmd_diff.go, cmd/plakar/cmd_find.go, cmd/plakar/cmd_ls.go, cmd/plakar/cmd_push.go, cmd/plakar/cmd_rm.go, cmd/plakar/cmd_tarball.go, snapshot/pull.go, snapshot/push.go, snapshot/snapshot.go, snapshot/snapshot_types.go, snapshot/tree.go, storage/fs/fs_store.go, ui/ui.go
=> Issue5 snapshot fsview

snapshot/importer/fs/fs.go
=> while mathieu refactors importer loading, resolve absolute path in

api/api.go, cmd/plakar/subcommands/ui/ui.go, ui/v2/ui.go
- pass the auth key to the UI entry point
- API middleware validates key
=> - generate auth key unless -no-auth is specified

cmd/plakar/subcommands/archive/archive.go
A few things in a single diff:
- correctly skip non directory/regular files
- write the tar headers for directories as well
- fix tarball generations: the gzip writer was closed *after* the file itself, and that was generating wrong tarballs
=> archive: simplify the code and fix the tarball generation

api/api.go, cmd/plakar/plakar.go, cmd/plakar/subcommands/clone/clone.go, cmd/plakar/subcommands/create/create.go, cmd/plakar/subcommands/sync/sync.go, repository/repository.go, server/plakard/server.go, storage/backends/database/database.go, storage/backends/fs/fs.go, storage/backends/http/client.go, storage/backends/null/null.go, storage/backends/plakard/client.go, storage/backends/s3/s3.go, storage/storage.go, storage/storage_test.go
remove bytes accounting, needs to be done at the repository level remove opt_stats, this will be turned into a prom exporter in agent mode
=> simplify storage layer by returning an interface

repository/repository.go
this was not pushed in latest commit
=> unbreak repository layer: ctx received but not set in Repository structure

btree/btree.go, btree/btree_test.go, btree/iter.go, btree/persist.go, btree/verify.go, caching/store.go, snapshot/store.go
backport of several addition, improvements and bugfixes for our BTrees.
The new features (backward iterator, Update) will be needed for the vfs-on-btree PR that I'm going to send once this lands.
It's probably easier to read this commit by commit rather than with the full diff.
=> btree improvements

go.mod, go.sum, storage/storage_test.go, testing/testing.go
This PR:
* add a new package `testing` that will contains commong testing mocks and interfaces
* refactor existing storage tests from whitebox to blackbox testing to avoid circular imports error
=> Create testing package

btree/btree.go, snapshot/backup.go, snapshot/errors.go, snapshot/vfs/vfs.go
just something i noticed while i was fixing the error accounting.  this simplifies a bit and allows to more easily plug a version check in the future.
=> factor btree deserialization

cmd/plakar/subcommands/ls/ls.go
Make sure the path is cleaned or the WalkDir callback breaks.
Do not print the named directory in its output.  In ls(1) you can achieve it only by passing -d, something which we don't have (and doesn't seem terribly useful in this context.)
Then, unless -recursive is passed, print only the entry name, not not its full path.
Fixes #273
=> fix some ls weirdnesses

packfile/packfile_test.go
before 
```
ok  	github.com/PlakarKorp/plakar/packfile	0.004s	coverage: 32.7% of statements
```
after
```
ok  	github.com/PlakarKorp/plakar/packfile	0.006s	coverage: 67.9% of statements
```
=> add packfile tests

api/api_repository_test.go, api/api_snapshot_test.go, testing/backend.go
not all endpoints are tested, this is the first batch until I have a working VFS mocked
=> add api snapshot tests

cmd/plakar/subcommands/restore/restore.go
Fix when giving the -to argument to restore with a non-fs exporter.
=> Fix restore initialization

cmd/plakar/subcommands/subcommands.go
This makes the output more consistent.
=> Sort subcommands

appcontext/appcontext.go
all commands need to receive a context.Context so we can handle interruption
=> add context to appcontext

storage/backends/s3/s3.go
it's not used, it doesn't match the storage interface, and no other backends use this
=> remove snapshots code from s3 storage backend

cmd/plakar/plakar.go
they will be reintroduced in Q2
=> remove keyring for now

cmd/plakar/plakar.go, cmd/plakar/subcommands/server/server.go, cmd/plakar/subcommands/stdio/stdio.go, storage/backends/plakard/client.go, storage/backends/plakard/client_test.go
- do not rebuild state in server mode, it is the client duty to rebuild on client side
- kill plakard server, we only support http servers for now
=> - server mode is agentless for the time being

snapshot/backup.go
leftover from my "stable shape" pr.
=> remove dead code

cmd/plakar/subcommands/mount/mount_freebsd.go, cmd/plakar/subcommands/mount/mount_windows.go
related to #357 ; don't have neither windows nor freebsd but this can't hurt.
=> fix build on freebsd and windows

api/api.go, api/api_snapshot.go, snapshot/search.go
The feature is not ready yet, and will be reimplemented later.
=> Remove snapshot search API endpoint

caching/repository.go, caching/scan.go, caching/state.go, repository/repository.go, repository/state/state.go
* /!\ Warning this is on top of #384, because this one might be a bit more controversial.
* let's you delete a snapshot by id by putting it into a dedicated list.
* While here do a bit of refactoring of the cache methods, as they grow
a bit too much for my liking.
=> state: Add DeleteSnapshot() operation

cmd/plakar/subcommands/clone/clone.go
Clone doesn't take any options.
=> Fix clone help message

storage/backends/s3/s3.go
We struggled to debug an error due to permissions because of the lack of context in errors messages. With this fix, it would have been easier.
=> s3: improve error messages on repository open failure

snapshot/errors.go
we don't want to end up calling yield again
=> fix iterator; should return not break

agent/agent.go, cmd/plakar/plakar.go
* When we fail to ExecuteRPC and fallback to agentless mode, we need to reopen the cache to actually use the agentless cache.
=> main: Fixup cache creation.

CRYPTOGRAPHY.md, cmd/plakar/subcommands/digest/digest.go, hashing/hashing.go, repository/repository.go
replace hmac-blake3 with keyed blake3 in ComputeHMAC
=> switch from HMAC-BLAKE3 to Keyed BLAKE3

cmd/plakar/subcommands/diag/contenttype.go, cmd/plakar/subcommands/diag/info.go, snapshot/backup.go
This is meant to be used in the future with the search functionality.
=> add a content-type index

api/api_repository_test.go, api/api_snapshot_test.go, api/api_test.go, cmd/plakar/subcommands/create/create.go, hashing/hashing.go, hashing/hashing_test.go, snapshot/snapshot_test.go, storage/serialization.go
=> use hashing.DEFAULT_HASHING_ALGORITHM

objects/fileinfo.go, snapshot/backup.go, snapshot/importer/fs/walkdir.go, snapshot/importer/fs/walkdir_windows.go, snapshot/importer/importer.go, snapshot/importer/importer_test.go, snapshot/vfs/xattr.go
This, unfortunately, needs (another) format break.
=> improve handling of different types of xattrs

cmd/plakar/subcommands/sync/sync.go, snapshot/snapshot.go, snapshot/snapshot_test.go, snapshot/vfs/errors.go, snapshot/vfs/vfs.go, snapshot/vfs/xattr.go
The code in here rotted a little bit while we were doing big changes on the repository.  Make it work again by leveraging the new interfaces (for e.g. the new vfs), and by trying to sync *everything*.
=> rework sync to that it actually works

cmd/plakar/subcommands/ls/ls.go, cmd/plakar/subcommands/ls/ls_test.go
and remove a forgotten print statement
=> fix ls subcommand tests

storage/backends/fs/fs.go, storage/backends/sftp/sftp.go
try unlinking it and then recreate it
=> when creating a repo, do not fail if the directory exists but is empty:

cmd/plakar/plakar.go, go.mod, go.sum
use pool.ntp.org for this PR but we're going to set an ntp server at plakar.io and switch to that in the next few days.
=> add an NTP validation at startup

cmd/plakar/subcommands/agent/agent.go, cmd/plakar/subcommands/cleanup/cleanup.go, cmd/plakar/subcommands/diag/diag.go, cmd/plakar/subcommands/diag/locks.go, network/types.go, repository/lock.go, repository/repository.go, resources/resources.go, server/httpd/httpd.go, snapshot/backup.go, snapshot/snapshot.go, storage/backends/database/database.go, storage/backends/fs/fs.go, storage/backends/http/client.go, storage/backends/null/null.go, storage/backends/s3/s3.go, storage/backends/sftp/sftp.go, storage/storage.go, testing/backend.go
WIP for the moment because we need BE implementation for sftp and S3.
=> WIP: Repository locking

storage/backends/fs/utils.go, storage/backends/s3/s3.go, storage/backends/sftp/utils.go
reader. diff untested at this point, I have exhausted my quota :-)
=> pass a NopCloser to minio PutObject, we don't want it to close our

snapshot/importer/fs/fs.go
=> plakar backup: preserve CWD when running in the agent

cmd/plakar/plakar.1
=> fix plakar man-page

cmd/plakar/subcommands/help/help.go, cmd/plakar/subcommands/help/help_test.go
+ fix help command return code when running happy path
=> add test for subcommand help

snapshot/backup.go
Debugged and fixed with gilles@ and mathieu@, thanks!
=> vfs: don't PutBlob() on the same thing more than once

snapshot/backup.go
=> we can't feed iterator bytes directly into the cache as they will

agent/agent.go, cmd/plakar/subcommands/agent/agent.go
This adds a simple version handshake when connecting to the daemon.  I tried to keep it as simple as possible: all it does is a ping-pong of the version.  If the version is not exactly the same, the client warns and falls back to agentless.
In theory we could have a protocol version for the agent, but I thought it was both more resiliant and user-friendly to just re-use plakar version.  (let's say we fix a bug on plakar that doesn't affect the protocol, should we still bump it to make the client complain?  i'm not sure)
I'm sending the version both ways because it may be useful for the agent to know which versions are connecting to it, not sure thought.  It didn't harm and seemed simple enough.
Finally, I'm avoiding phrases like "please update" to 1) keep the error below 80 columns and 2) …
=> agent: add a version handshake

README.md
Explain a bit better the value proposition of Plakar.
=> Update readme to better explain plakar value proposition.

storage/backends/s3/s3.go
Some S3-compatible providers, such as Backblaze, do not support the x-amz-checksum-algorithm header and return an error when it is used.
To improve compatibility, the client now computes and sends an MD5 checksum instead. This ensures broader provider support at the cost of additional resource usage.
In the future, we can make this behavior configurable if needed.
=> Fix s3 for blackblaze and alternative providers

btree/cache.go
in the backup phase we're running behind an exclusive lock, but during restore (or ls, ui, etc...) there's just a shared read lock that's not enough to protect the cache.
=> btree/cache: protect cache changes with a mutex

snapshot/packer.go
that might cause some checks to indicate a blob does not exist while
it was PutBlob but not processed yet by the packer
=> move inflights marking earlier to PutBlob, removes a race condition

api/api.go
=> perform a constant time comparison, suggested by @semarie

storage/backends/s3/s3.go
It was very annoying not knowing which function call caused an error..
=> s3 storage: wrap errors

cmd/plakar/subcommands/maintenance/maintenance.go
* Load new snapshots in the cache in parallel since this is the most expensive operation.
* We still have to parallelize the inner loop of those but this is a bigger work.
=> maintenance: Parallelize cache update.

.github/workflows/build.yml, .github/workflows/go.yml
10 minutes should be plenty for what we have now.
=> github: set {build,go} timeout to 10 minutes

api/api.go, api/api_repository.go, api/api_snapshot.go, snapshot/search.go
extend search to apply a namefilter
=> Poolp org/api locate

cmd/plakar/plakar.go
This reverts commit f991169f6c3f16dccb1c8607b9bfd020a8c8de1d.
=> Revert "Parse the command-line earlier, now that the repository is not needed."

api/api_snapshot.go, cmd/plakar/subcommands/diag/diag.go, cmd/plakar/subcommands/diag/search.go, snapshot/search.go
Also, the command plakar diag <snapshot> <mimes> now accepts a commas separated string.
=> api: allow searching files with several mimes

api/api_snapshot.go, cmd/plakar/subcommands/diag/search.go, snapshot/search.go
If the user cancels the request, cancel the search too.
=> api search: pass the request context

caching/check.go
actually from @mathieu-plak ; i didn't want this to get lost.
=> caching: actually remove the check cache

cmd/plakar/subcommands/version/version.go, cmd/plakar/subcommands/version/version_test.go, storage/backends/null/null.go
=> display registered backends

cmd/plakar/subcommands/backup/backup.go, cmd/plakar/subcommands/maintenance/maintenance.go, cmd/plakar/subcommands/sync/sync.go, repository/packer/packer.go, repository/repository.go, repository/repositorywriter.go, snapshot/backup.go, snapshot/builder.go, snapshot/check.go, snapshot/indexes.go, snapshot/packer.go, snapshot/snapshot.go, snapshot/store.go, snapshot/synchronize.go, snapshot/verify.go, testing/snapshot.go
* Snapshot shouldn't deal with states at all, so move everything under the umbrella of the repository
* Foundation for moving more code to the repository.
=> repo: Move deltaState to the repo level.

.github/workflows/go.yml
This enables running of the go.yml workflows for all PRs, regarding whether they target main or another branch.
=> run build and tests for all PRs

go.mod, go.sum
0.4.0 was retired and it's broken
=> downgrade anacrolix/fuse to 0.3.1

cmd/plakar/plakar.go
=> cmd: Disallow usage of at for agent cmd.

sftp/sftp.go
* move the bulk of the config into parseconfig resolveSSHConfig (now parseconfig)
* use a struct for the config instead of a untype map string to string.
=> sftp: refactor config parsing

cmd/plakar/subcommands/check/check.go
* seems like you can't do an omelet without breaking some eggs ....
=> cmd/check: Fix snapshot parsing.

storage/backends/ptar/ptar_test.go
it doesn't really test the self contained ptar part so these tests are probably not enough
=> add ptar storage backend test

btree/btree_test.go, btree/memorystore.go, caching/lru/lru.go, caching/store.go, cli/entrypoint.go, network/types.go, objects/fileinfo_unix.go, objects/objects.go, plakarfs/dir.go, plakarfs/file.go, plakarfs/fs.go, snapshot/archive.go, snapshot/importer/sftp/walkdir.go
* Not a fan of this kind of commits, but the changestat is actually small, and it avoids having those done randomly as part of other unrelated series.
=> misc: gofmt the full codebase.

.github/workflows/build.yml, .github/workflows/go.yml, .github/workflows/update-plakar-ui.yml
This should get rid of the last github "security issues".
=> github: add permissions to the various workflows

caching/caching.go
we might end up double closing the cache due to some minor shenanigans with caches being re-opened and defer in the mix, so work aronud that.
=> caching: handle gracefully a cache double-close

agent/agent.go, appcontext/appcontext.go, cli/entrypoint.go, cmd/plakar/subcommands/agent/agent.go, cmd/plakar/subcommands/clone/clone.go, cmd/plakar/subcommands/digest/digest.go, cmd/plakar/subcommands/locate/locate.go, cmd/plakar/subcommands/ls/ls.go, cmd/plakar/subcommands/maintenance/maintenance.go, cmd/plakar/subcommands/mount/fuse.go, cmd/plakar/subcommands/ptar/ptar.go, cmd/plakar/subcommands/sync/sync.go, repository/packer/packer.go, server/httpd/httpd.go, snapshot/archive.go, snapshot/backup.go, snapshot/check.go, snapshot/exporter/s3/s3.go, snapshot/importer/fs/fs.go, snapshot/importer/fs/walkdir.go, snapshot/importer/fs/walkdir_windows.go, snapshot/importer/s3/s3.go, snapshot/restore.go, storage/backends/s3/s3.go, ui/v2/ui.go
Handle cancellation in agent and non-agent.
=> cancellation, cancellation everywhere

snapshot/backup.go, snapshot/importer/fs/fs.go
=> fix backup hang

cmd/plakar/subcommands/login/login.go, cmd/plakar/subcommands/login/logout.go
=> make sure login is performed on the agent, in agent mode

snapshot/importer/fs/fs.go
* We need to actually try to resolve the rootDir before attempting the scan otherwise we can't properly bubble up the error (yet).
* While here rename the varial "real" to "realp" as real is a go builtin func.
=> importer/fs: Fix error reporting when rootdir doesn't exist.

cmd/plakar/subcommands/backup/backup.go, cmd/plakar/subcommands/info/repository.go, logging/logging.go
do not show efficiency in the CLI
=> do not prepend time to logs, syslog does it

utils/btreescan/main.go
As a side effect this will make it easier to test (let's us swap the importer).
=> btreescan: use config + all importers.

cmd/plakar/utils/utils.go
This is the second part needed for #922.  It means that it'll be possible to run the following and still being able to prompt the user for a password, assuming a tty is available:
$ pgdump | plakar backup stdin://tmp/foo
repository passphrase: ***
[...]
=> try to use the tty for the passphrase prompts

main.go
=> support passphrase_cmd in config

connectors/fs/importer/fs.go
This adds a knob for the fs importer to not traverse filesystems during a backup.  The idea is that we keep track of the device number for the root of the backup and we skip all the directories that belong to a different device.
The new knob is called dont_traverse_fs and at the moment has to be specified by creating a "remote" config stanza with a trueish value ("1", "t", "T", "true", "TRUE" or "True").
=> importer/fs: add knob to not traverse filesystems

main.go, subcommands/agent/agent_test.go, subcommands/backup/backup_test.go, subcommands/config/config_test.go, subcommands/create/create_test.go, subcommands/help/help_test.go, testing/repository.go
depends on: https://github.com/PlakarKorp/kloset/pull/38
=> kcontext thinning

go.mod, go.sum, subcommands/ptar/ptar.go
* It's not usable anymore after ptar creation.
=> ptar: Delete the vfs cache.

.github/workflows/release.yml, .gitignore, .goreleaser.yml
Before merging this pull request, we need to create a token with read/write permissions on "Contents" for the repository https://github.com/PlakarKorp/homebrew-tap/
Then we need to configure this repository to store the token in the secret variable `HOMEBREW_TOKEN`.
Then to use the tap:
```bash
brew install PlakarKorp/tap/plakar
```
=> Setup goreleaser

connectors/grpc/storage/grpc_storage.go
-renamed `sendChunks` to `SendChunks` and `receiveChunks` to `ReceiveChunks` to export them
-updated PutX methods to explicitly handle errors when sending the initial MAC message
-simplified chunk-handling logic
this PR mainly exist for furthur optimisation in the SDK
=> refactors the `GrpcStorage` implementation

subcommands/pkg/build.go
This adds a way to build a package given a recipe.
=> add pkg build

connectors/fs/storage/buckets.go, connectors/fs/storage/fs.go, connectors/fs/storage/utils.go, connectors/sftp/storage/buckets.go, connectors/sftp/storage/sftp.go, connectors/sftp/storage/utils.go, go.mod, go.sum
=> use new kloset/reading helpers

subcommands/login/token.go, utils/login.go
to generate a new token fom the current one.
=> implement a "token create" command

api/api.go, api/api_authentication.go, api/api_proxy.go, api/api_repository.go, api/api_snapshot.go, api/api_snapshot_test.go, server/httpd/httpd.go, subcommands/server/server.go
this makes impossible to use multiple UI instances in the agent since the second one overrides the first' state.
=> api: get rid of the global state

go.mod, go.sum, subcommands/backup/backup.go
c.f. https://github.com/PlakarKorp/kloset/pull/59
=> adapt to kloset change for excludes

subcommands/pkg/add.go, subcommands/pkg/build.go, subcommands/pkg/create.go, subcommands/pkg/pkg.go, subcommands/pkg/rm.go
turns out the order of registration is important.
=> move plugin registration

api/api_proxy.go, appcontext/appcontext.go, scheduler/scheduler.go, task/task.go
Use AppContext.GetCookies().GetAuthToken() directly instead.
=> Remove AppContext.GetAuthToken(repositoryID) entirely.

plugins/manifest.go, plugins/plugin_loader.go, subcommands/pkg/create.go
- add a dedicated loader
- make sure that the version starts with a 'v'
=> move manifest to its own file

api/api_params.go, api/api_snapshot.go
so that we can return the right http code.
if my sweep is complete, this should fix https://github.com/PlakarKorp/plakar/issues/1347.
=> api: add missing wrappers

api/api.go
The demo mode is enabled on demo.plakar.io. With this mode, only read-only API endpoints are enabled. The UI is using the flag returned by /api/info to know whether to run in the demo mode or not, and disable the calls to the endpoints non-existing in demo mode.
=> Enable demo mode with env PLAKAR_DEMO_MODE

plugins/recipe.go, subcommands/pkg/add.go, subcommands/pkg/build.go
move recipe code into its own module
=> make 'pkg add' accept a simple plugin name like 'pkg build'

main.go, subcommands/agent/agent.go, subcommands/subcommands.go
=> pass command line to agent so it's recorded properly in snapshot header,

go.mod, go.sum, main.go, plugins/integration.go, plugins/manager.go, plugins/package.go, plugins/plugin_loader.go, plugins/recipe.go, subcommands/help/docs/plakar-pkg-add.md, subcommands/pkg/add.go, subcommands/pkg/build.go, subcommands/pkg/fetch.go, subcommands/pkg/pkg.go, subcommands/pkg/plakar-pkg-add.1, subcommands/pkg/plakar-pkg.1, subcommands/pkg/rm.go
- require the user to be logged in for fetching packages.
- unregister backends when removing a package
- factorize/simplify code in subcommands
=> fixes and improvements on plugins

main.go
=> remove undocumented -hostname and -username, they're not needed

subcommands/help/docs/plakar-login.md, subcommands/login/login.go, subcommands/login/plakar-login.1, subcommands/pkg/add.go, subcommands/pkg/fetch.go
- misplaced defer
- fix check for urls that require login
- add a `-status` option to `login` command`
=> fix pkg add

api/api_authentication.go, login/login.go, subcommands/login/login.go, subcommands/login/logout.go
- do not accept extra arguments in login and logout subcommands
- report an error on logout if the user is not logged
=> login doesn't happen in a repository context

subcommands/help/docs/plakar-agent.md, subcommands/help/docs/plakar-login.md, subcommands/help/docs/plakar-logout.md, subcommands/help/docs/plakar-scheduler.md, subcommands/login/plakar-login.1, subcommands/login/plakar-logout.1
=> 1207 create manpage for plakar logout

utils/browser.go
=> try browser fallbacks

subcommands/help/docs/plakar-token.md, subcommands/login/plakar-token.1, subcommands/login/token-create.go, subcommands/login/token.go
* disallow extra arguments
* add man page
* fix short message
=> plakar token: improve help

plugins/package.go, subcommands/pkg/add.go, subcommands/pkg/build.go, subcommands/pkg/create.go, subcommands/pkg/pkg.go, subcommands/pkg/rm.go
display version name in pkg list while here
=> fix -h on pkg subcommands

api/api_snapshot.go, go.mod, go.sum, subcommands/cat/cat.go, subcommands/diag/diag_test.go
Adapt to changes in : https://github.com/PlakarKorp/kloset/pull/103
While here fix an unrelated breakage in tests.
=> Adapt to VFS's Open change

subcommands/help/help.go
fixes the other issue outlined in https://github.com/PlakarKorp/plakar/issues/1567
=> help: handle sub-subcommands

subcommands/pkg/pkgimporter.go
while here revert a typo on the error message.
=> plugin: fix executable check on !windows

ui/v2/ui.go
Instead of having several manual cases, we use http.FileServer to serve everything and we call http.ServeFileFS only in the case the requested file doesn't exist.
=> ui: simplify serving assets
