storage/backends/fs/fs.go

adding an extra check costs nothing and will shut static analysis false positives

be extra paranoid with pathnames, input is properly sanitized but

---

api/api_repository.go
repository/repository.go

by any long-standing command to catch up on new snapshots that happened since the command was launched

make rebuildState public so it can be called externally, most notably

---

cmd/plakar/plakar.go
cmd/plakar/utils/utils.go

Instead of checking for updates at every invocation, try to check at most daily.
Not a fan of the stat + open TOCTOU, but I don't know a better way around.  We could `open(O_RDWR|O_CREATE)` but then we don't know if we're the ones that created the file or it was created by someone else very recently.
This means that concurrent plakar processes with the wrong timing could all end up checking for update, but at least it's only an issue for concurrent invocations.
I've also tried to simplify CheckUpdate a bit.  it's probably easier to read the two commits one by one instead of the cumulative diff.

don't check update at every invocation

---

ui/v2/ui.go

For requests containing a Authorization header, the browser generates a pre-flight request that requires the response to contain a header Access-Control-Allowed-Headers containing Content-Type and Authorization.

Set CORS Allowed-Headers

---

cmd/plakar/subcommands/info/info.go
snapshot/backup.go
snapshot/vfs/fileEntry.go

the wrong record type is recorded in file summaries leading to

---

api/api_snapshot.go

in snapshotVFSChildren we're dealing with the objects sort keys, not the header ones.
Spotted by Julien Castets, thank you!

fix sort param validation broken in previous

---

chunking/chunking_test.go
go.mod
go.sum
repository/repository.go

noticed after the typo on the readme; we were still using go-cdc-chunkers from PlakarLabs.

use go-cdc-chunkers from PlakarKorp

---

btree/btree.go
btree/btree_test.go
btree/iter.go
snapshot/backup.go
snapshot/errors.go

it was a bad idea.  I've introduced because I thought it could have been handy for customizing the start of the iteration, but in practice it's just a footgun in the btree API.

remove explicit comparer from ScanFrom

---

cmd/plakar/subcommands/checksum/checksum.go
cmd/plakar/subcommands/diff/diff.go
snapshot/check.go
snapshot/restore.go
snapshot/vfs/dirEntry.go
snapshot/vfs/fileEntry.go
snapshot/vfs/vfilep.go
snapshot/vfs/vfs.go

filepath is a package that "implements utility routines for manipulating filename paths in a way compatible with the target operating system-defined file paths", as such it may use for e.g. forward or backward slashes depending on the OS.
path, instead, manipulates paths such as URLs that always use forward slashes, and it's what should be used when we handle backup paths internally.
lightly tested, and only on linux, but should help with Windows :)

fix cross-OS path handling

---

snapshot/importer/fs/walkdir.go

do not craft a children array, kill dead code

since big dir refacto, we no longer need to opendir/readdir as we

---

btree/iter.go

was an attempt at getting the container address, but it's the wrong way to expose that information: in case we need to iterate over nodes we can use a different iterator.

btree: remove the Node() method

---

repository/repository.go

This is another bit extracted from my vfs branch.  I'll need this to implement ReadSeeker on top of a fs.File for the API layer (in particular for the http.ServeContent in api_snapshot.go).
The main downside, and also why I'm extracting this into its own PR is because of the s/NewBuffer/NewReader/ change: a reader keeps all the data in memory while the reader is used, while the buffer removes it as it's read.  Didn't want to hide that in the much bigger vfs diff.

make GetPackileBlob return a ReadSeeker

---

btree/btree_test.go
btree/iter.go
btree/verify.go

was added as a quick way to debug the tree, but Dot is better in that regard, and `VisitLevelOrder` just needs a lot of memory for nothing.
While here, improve the Dot method a tiny bit.

retire btree.VisitLevelOrder

---

caching/scan.go
cmd/plakar/subcommands/archive/archive.go
cmd/plakar/subcommands/sync/sync.go
plakarfs/dir.go
repository/repository.go
repository/state/state.go
snapshot/errors.go
snapshot/search.go
snapshot/snapshot.go
snapshot/vfs/vfs.go

The only drawback is that now we don't pre-compute the next element in a different goroutine while the consumer handles the previous one, but the advantage is that we're no longer leaking goroutines when a consumer `break`s out of a loop.  I converted everything except the importers and `ListStates` since Mathieu is working on that area.

convert existing channels to proper iterators

---

api/api_params.go
api/api_params_test.go

before
```
github.com/PlakarKorp/plakar/api/api_params.go:13:	PathParamToID			0.0%
github.com/PlakarKorp/plakar/api/api_params.go:34:	QueryParamToUint32		0.0%
github.com/PlakarKorp/plakar/api/api_params.go:56:	QueryParamToInt64		0.0%
github.com/PlakarKorp/plakar/api/api_params.go:71:	QueryParamToSortKeys		0.0%
```
after
```
github.com/PlakarKorp/plakar/api/api_params.go:12:	PathParamToID			100.0%
github.com/PlakarKorp/plakar/api/api_params.go:33:	QueryParamToUint32		100.0%
github.com/PlakarKorp/plakar/api/api_params.go:51:	QueryParamToInt64		100.0%
github.com/PlakarKorp/plakar/api/api_params.go:65:	QueryParamToSortKeys		100.0%
```
I also removed some dead code that was never executed and fixed the Uint64 parsing

add api params test

---

api/api_test.go

before
```
github.com/PlakarKorp/plakar/api/api.go:33:		ServeHTTP			0.0%
github.com/PlakarKorp/plakar/api/api.go:42:		handleError			0.0%
github.com/PlakarKorp/plakar/api/api.go:70:		AuthMiddleware			0.0%
github.com/PlakarKorp/plakar/api/api.go:89:		NewRouter			0.0%
```
after
```
github.com/PlakarKorp/plakar/api/api.go:33:		ServeHTTP			75.0%
github.com/PlakarKorp/plakar/api/api.go:42:		handleError			58.3%
github.com/PlakarKorp/plakar/api/api.go:70:		AuthMiddleware			80.0%
github.com/PlakarKorp/plakar/api/api.go:89:		NewRouter			100.0%
```

add tests for api core methods

---

api/api.go
api/api_params.go
api/api_params_test.go
api/api_repository.go
api/api_snapshot.go
api/api_storage.go
api/api_test.go
ui/v2/ui.go

gorilla/mux is not maintained anymore, and the routing enhancements of go 1.22 (https://go.dev/blog/routing-enhancements) make it possible to only use the stdlib.
mux is still used in server/httpd/httpd.go so the dependency can't be removed yet.

Stop using gorilla/mux in the API

---

api/api.go
api/api_repository.go
api/api_snapshot.go
api/api_storage.go

This is nitpicking. The types Item and Items used to return a single object and a list of objects in the API were holding a reference to an interface.
Now, instead, the structs take a generic type as a parameter.

Avoid generic interface{} and use generic types instead

---

snapshot/backup.go

when we scan the files we first put a Entry structure in the index and only later we consult the cache to see if we've already chunkified it.
The issues is that we have to update it even in the case the entry was found in the cache, otherwise we leave the Objects field to nil in the backup and the file content are not available.

update the btree even when the file was found in the cache

---

snapshot/backup.go
snapshot/vfs/entry.go
snapshot/vfs/vfs.go

The issue is that basically we're summing not only the errors of a given directory, but also all the errors in its subdirectories.
A better fix would be to restructure a bit how we backup: assuming we record the intermediate directories before their children, we wouldn't have to do this second pass but just grab the temporary directory entry and update the stats there, but for now this should do it.
While here, also factor out that bit of code to avoid some repetition.

fix total error accounting

---

cmd/plakar/subcommands/ls/ls.go
snapshot/vfs/walk.go

This works similarly to fs.WalkDir, but it's slightly more optimized for our use case: the std one has to read all the child entries in memory before processing them, while this implementation relies on the fact that the VFS layer returns the child entries already sorted.

vfs: provide a WalkDir implementation

---

cmd/plakar/subcommands/info/info.go
repository/state/state.go
repository/state/state_test.go

* For space optimization reasons, we were using uint64 indices in place of the real checksums. This commit moves us back to using checksum indices. This is indeed bad but it's in preparation for moving the state handling to disk rather than memory, where we don't really care about space but we'd like to get rid of the complexity of mapping checksums.
* Warning: this breaks the ondisk format of repository so be sure to trash your repo and caches before using it.
* This is _mostly_ mechanical but warrants a bit of care / proper review.

state: Move indices to checksums.

---

cmd/plakar/utils/utils.go

nit i spotted while investigating something else.  At first I thought we could `path.Clean` in here, but the second part after the `:` is not guaranteed to be a path (e.g. see `plakar find` whose manpage could use an update :P).

use SplitN in ParseSnapshotID

---

cmd/plakar/subcommands/backup/backup.go
snapshot/backup.go

We always try first with what was given on the command line (or the current working directory); if that fails, maybe because it looks like like a URI but we don't support its "protocol", we still try to resolve it as a filesystem path.

simplify importer selection logic

---

snapshot/vfs/entry.go

To initialize a slice, the capacity should use the third argument of make and not the second one.

Fix extended attributes

---

logging/logging_test.go

before
```
github.com/PlakarKorp/plakar/logging		coverage: 0.0% of statements
```
after
```
ok  	github.com/PlakarKorp/plakar/logging	0.002s	coverage: 100.0% of statements
```

add logging tests

---

objects/fileinfo.go
objects/fileinfo_test.go
objects/fileinfo_windows.go
testing/fileinfo/fileinfo.go

+ fix an issue with nlink not using the constructor value
before
```
github.com/PlakarKorp/plakar/objects/fileinfo.go:33:	Name			0.0%
github.com/PlakarKorp/plakar/objects/fileinfo.go:37:	Size			0.0%
github.com/PlakarKorp/plakar/objects/fileinfo.go:41:	Mode			0.0%
github.com/PlakarKorp/plakar/objects/fileinfo.go:45:	ModTime			0.0%
github.com/PlakarKorp/plakar/objects/fileinfo.go:49:	Dev			0.0%
github.com/PlakarKorp/plakar/objects/fileinfo.go:53:	Ino			0.0%
github.com/PlakarKorp/plakar/objects/fileinfo.go:57:	Uid			0.0%
github.com/PlakarKorp/plakar/objects/fileinfo.go:61:	Gid			0.0%
github.com/PlakarKorp/plakar/objects/fileinfo.go:65:	IsDir			0.0%
github.com/PlakarKorp/plakar/objects/fileinfo.go:69:	Nlink			0.0%
github.com/PlakarKorp/plakar/objects/fileinfo.go:73:	Sys			0.0% …
```

add missing tests for fileinfo

---

objects/objects.go
snapshot/vfs/entry.go

I'm not 100% sure this is enough. I believe we need to review all the API endpoints to make sure omitempty is set where it should, and not set where it shouldn't.
This will break the UI, but the branch jcastets/fix-omitempty is prepared to be merged.

Add omitempty to JSON outputs

---

appcontext/appcontext_test.go
compression/compression_test.go
hashing/hashing_test.go

before
```
ok  	github.com/PlakarKorp/plakar/hashing		0.003s	coverage: 87.5% of statements
ok  	github.com/PlakarKorp/plakar/appcontext		0.005s	coverage: 56.1% of statements
ok  	github.com/PlakarKorp/plakar/compression	0.043s	coverage: 82.0% of statements
```
after
```
ok  	github.com/PlakarKorp/plakar/hashing		0.003s	coverage: 100.0% of statements
ok  	github.com/PlakarKorp/plakar/appcontext		0.009s	coverage: 100.0% of statements
ok  	github.com/PlakarKorp/plakar/compression	0.048s	coverage: 90.0% of statements
```

Add missing tests

---

events/events.go
events/events_test.go

before
```
ok  	github.com/PlakarKorp/plakar/events	0.002s	coverage: 15.8% of statements
```
after
```
ok  	github.com/PlakarKorp/plakar/events	0.004s	coverage: 100.0% of statements
```

add tests for events package

---

storage/backends/database/database.go
storage/backends/null/null.go
storage/backends/s3/s3.go

doesn't seem to be used anywhere and not defined on the main storage.Store interface

remove commit method from storage backends

---

storage/storage_test.go
testing/backend.go

before
```
ok  	github.com/PlakarKorp/plakar/storage	0.003s	coverage: 38.6% of statements
```
after
```
ok  	github.com/PlakarKorp/plakar/storage	0.007s	coverage: 96.5% of statements
```

add storage tests

---

objects/objects.go
objects/objects_test.go

to avoid errors like 
```
json: cannot unmarshal string into Go value of type objects.Checksum
```

fix checksum json unmarshalling

---

btree/btree_test.go
btree/persist.go
cmd/plakar/subcommands/sync/sync.go
packfile/packfile.go
packfile/packfile_test.go
repository/state/state.go
snapshot/backup.go
snapshot/store.go
snapshot/vfs/entry.go
snapshot/vfs/vfs.go

For this, and to avoid changing too much the structure of backup.go, `btree.Persist` needs to learn how to convert the values: it allows to build the BTree as we're doing now, and deal with the checksums only when we have to persist the entries too.

rework the VFS so the BTree stores only the checksum of the entry

---

storage/backends/plakard/client_test.go

I only tested the TCP client part, this will probably need to be refactored later to use a real plakard server instead of a mocked one.
before
```
github.com/PlakarKorp/plakar/storage/backends/plakard		coverage: 0.0% of statements
```
after
```
ok  	github.com/PlakarKorp/plakar/storage/backends/plakard	0.006s	coverage: 53.9% of statements
```

add storage backend plakard tests

---

snapshot/backup.go

* This used to be done to convert from the byte slice to the Checksum type. The repository.Checksum function now returns a Checksum so remove the now useless copy.

snap: Remove an useless copy in PutPackfile()

---

snapshot/importer/fs/walkdir.go

* On nss enabled system, doing the username and groupname lookup is heavy (at least two syscalls) so let's use a local cache mapping uid/gid to names.
* This version is using an RWMutex making the diff slightly bigger than expected, but I think it's worth it, since the load is intrisically read-heavy.
* On Linux, this is a 200X speedup doing a pure fs import of the linux file source tree (from 40s down to 0.2s seconds run.)

importer:fs: Implement a simple usr/grp name cache.

---

cmd/plakar/plakar.go

this allows running agentless commands while the agent is running without interfering

do not share cache between agent mode and agentless

---

snapshot/check.go

on non-regular files instead of skipping them for chunking

when I rewrote check to use the VFS, I mistakenly reported an error

---

cmd/plakar/plakar.go
cmd/plakar/subcommands/create/create.go
cmd/plakar/subcommands/info/info.go
cmd/plakar/subcommands/sync/sync.go
encryption/encryption_test.go
encryption/symmetric.go

long story short:
We don't need to store the encrypted master key in the repository config as if we store the KDF parameters and salt, we can derive the same master key from the passphrase and config parameters.
Adding a canary field with encrypted random data, we can rely on the GCM integrity check to validate that the passphrase supplied was the same as during repository configuration without leaking any useful informations.

rework encryption

---

caching/repository.go
caching/scan.go
caching/state.go
cmd/plakar/subcommands/info/info.go
repository/repository.go
repository/state/state.go
snapshot/snapshot.go

* Basic idea is to have a "generation number" like serial, that will let us deal with maintenance by detecting compacted / aggregated state.
* Initial serial is the repository id to avoid any race issues with concurrent first time backups.

state: Implement a serial number for states.

---

snapshot/backup.go

Not sure if this is everything.  For examples, if i backup `/home/op/w/plakar/btree` i get this `info vfs` back:
```
[DirEntry]
Version: 2
ParentPath: /
Name: /
Type: 1
Size: 4.1 kB (4096 bytes)
Permissions: drwxr-xr-x
ModTime: 2024-07-24 09:59:59.463964813 +0200 CEST
DeviceID: 65025
InodeID: 2
UserID: 0
GroupID: 0
Username: root
Groupname: root
NumLinks: 20
ExtendedAttributes: []
FileAttributes: 0
Classification:
CustomMetadata: []
Tags: []
Below.Directories: 0
Below.Files: 7
Below.Symlinks: 0
Below.Devices: 0
Below.Pipes: 0
Below.Sockets: 0
Below.Setuid: 0
Below.Setgid: 0
Below.Sticky: 0
Below.Objects: 7
Below.Chunks: 7
Below.MinSize: 0 B (0 bytes)
Below.MaxSize: 6.9 kB (6907 bytes)
Below.Size: 26 kB (26442 bytes)
Below.MinModTime: 1970-01-01 01:00:00 +0100 CET
Below.MaxModTime: …
```

fix (some) summary accounting

---

cmd/plakar/subcommands/create/create.go

it fixes `echo | plakar create` that was previously an infinite loop, but it's still not possible to provide the passphrase through a pipe.

create: avoid infinite loop if stdin is a pipe

---

hashing/hashing.go
repository/repository.go

this will be used to generate HMAC for the storage file format and for privacy-friendly lookup keys

let repository provide a HMAC hasher preset with repository master key and a ChecksumHMAC helper

---

caching/repository.go
caching/scan.go
caching/state.go
repository/repository.go
repository/state/state.go

* This allows us to skip unknown entry types (for forward compat')

state: Serialize length of entry alongside its type.

---

cmd/plakar/subcommands/create/create.go
go.mod
go.sum

bypassing with -weak-passphrase as this can still be useful if a
passphrase is deemed secure by the user despite our warnings and
they still want to encrypt the passphrase with it rather than to
go `-no-encryption`

teach plakar how to hint at providing a proper passphrase, allow

---

repository/repository.go
repository/state/state.go
snapshot/backup.go

* This way we don't have to go through the index to check a blob version.
* While here remove an old function that is unused anymore, reducing the number of way we push DeltaEntries to the state.

state: Save blob version when pushing them.

---

cmd/plakar/subcommands/ls/ls.go
objects/fileinfo.go
objects/fileinfo_test.go

before:
```sh
$ plakar ls 80
2024-07-24T07:59:59Z drwxr-xr-x                     4.1 kB /
$ plakar ls 80:/
2024-07-16T17:11:30Z drwxr-xr-x                     4.1 kB home
```
now:
```sh
$ plakar ls 80
2024-07-16T17:11:30Z drwxr-xr-x                     4.1 kB home
```
I was tempted to change `utils.ParseSnapshotId` to return `"/"` instead of the empty string, but that's useful in some commands to disambiguate with the wrong usage, so changing only ls for now.

improve ls snapshotID

---

snapshot/vfs/entry.go
snapshot/vfs/vfs.go

* This used to be private but now that we have a way of iterating over nodes (and as a result the checksum entries) it makes sense to have this public rather than coding it ad-hoc everywhere, especially since this does quite a bit of things.

vfs: Export ResolveEntry()

---

snapshot/errors.go

* We store the nodes as RT_ERROR_BTREE so when loading the BTREE use the same type.

errors: Fix btree ressource type.

---

cmd/plakar/subcommands/info/repository.go
encryption/symmetric.go
go.mod
go.sum

Following crypto audit, it was suggested as an improvement to switch to AES256-GCM-SIV:
**We recommend switching to AES-GCM-SIV for chunk encryption.**
AES-GCM-SIV is a mode defined in [RFC 8452](https://www.rfc-editor.org/rfc/rfc8452.html) that does not rely on
randomness. It produces the nonce by computing a PRF over the message to
encrypt. It implies that encrypting the same message twice will produce
the same ciphertext. However, if each subkey encrypts a single chunk,
this is not an issue.
AES-GCM-SIV also prevents streaming of the data hashed, therefore the
whole chunk has to be stored in memory. Since data is already chunked to
be streamed, and chunks are of fixed, small size (64 KB), this is not an
issue.
That said, AES-GCM-SIV has less adoption than AES-GCM, and is not as …

switch to AES256-GCM-SIV

---

api/api_snapshot.go
caching/scan.go
cmd/plakar/subcommands/backup/backup.go
cmd/plakar/subcommands/diag/errors.go
cmd/plakar/subcommands/diag/vfs.go
cmd/plakar/subcommands/info/vfs.go
objects/fileinfo.go
objects/fileinfo_windows.go
resources/resources.go
snapshot/backup.go
snapshot/filesystem.go
snapshot/header/header.go
snapshot/importer/fs/fs.go
snapshot/importer/fs/walkdir.go
snapshot/importer/fs/walkdir_windows.go
snapshot/importer/fs/xattr.go
snapshot/importer/ftp/ftp.go
snapshot/importer/importer.go
snapshot/importer/s3/s3.go
snapshot/reader.go
snapshot/vfs/entry.go
snapshot/vfs/errors.go
snapshot/vfs/reader.go
snapshot/vfs/vfs.go
snapshot/vfs/xattr.go
testing/backend.go

Since these can be varying in size (on darwin for example), we're tracking their content in an object like it were a file itself but to avoid cluttering the "real" VFS, we're keeping these entries in their own tree which the VFS package take care of.
The interface to handle xattrs will be improved in subsequent commits.

vfs: add another btree for extended attributes

---

api/api_params_test.go
api/api_repository_test.go
api/api_snapshot_test.go
api/api_test.go
cmd/plakar/plakar.go
cmd/plakar/subcommands/agent/agent.go
cmd/plakar/subcommands/sync/sync.go
repository/repository.go
server/plakard/server.go
snapshot/snapshot_test.go

once in the appcontext and once in the repository

simplify repository constructor so we don't store the key twice,

---

cmd/plakar/subcommands/diag/packfile.go
packfile/packfile.go
packfile/packfile_test.go
snapshot/packer.go

where it would help us in the future: being able to know pre-deserialization
that a blob has to be handled in a specific way.

add flags to packfiles and packfiles blob indexes, we spotted a case

---

btree/iter.go
iterator/iter.go
snapshot/vfs/entry.go
snapshot/vfs/errors.go
snapshot/vfs/vfs.go

it's helpful to have this kind of "iter.Seq3" iterators around, could be used in other places as well.

move the btree.Iterator interface to its own package

---

cmd/plakar/plakar.go

* Because a short variable form declaration was used the err variable was local and shadowed the global one, therefore when out of the inner scope the global err was nil and nothing was logged.

plakar: Fix implicit agentless error reporting.

---

snapshot/backup.go
snapshot/importer/fs/walkdir.go
snapshot/importer/importer.go
snapshot/importer/importer_test.go
utils/btreescan/main.go

We concatenate the path with the name of the xattr, and then feed this constructed bogus path to NewExtendedAttributeReader which can't work.
Instead, keep separate the two information until we actually have to insert something in the btree.

fix handling of xattrs

---

cmd/plakar/plakar.go
cmd/plakar/subcommands/create/create.go
cmd/plakar/subcommands/create/plakar-create.1
cmd/plakar/subcommands/help/docs/plakar-create.md
repository/repository.go

plakar create is the only command that takes a repository path as parameter rather than using the `on` construct, which makes it confusing as:
plakar on /tmp/foobar create
does not do what you expect, fix this.

make sure create uses the same feel as other commands

---

btree/btree.go
cmd/plakar/subcommands/diag/contenttype.go
cmd/plakar/subcommands/diag/xattrs.go
resources/resources.go
snapshot/backup.go
snapshot/store.go
snapshot/vfs/errors.go
snapshot/vfs/vfs.go
snapshot/vfs/xattr.go

Unfortunately another break, but I think we need to differentiate between the root wrapper structure and the node structures, since they're completely different structures.  This makes both recovering easier to do, but also simplifies some future work I'd like to do with sync/colouring.

differentiate between resource versions for btree root wrapper and nodes

---

caching/scan.go
snapshot/backup.go

* While here remove this whole caching API, it's unused nowadays.

backup: Remove scan.PutMAC() call in backup.

---

snapshot/snapshot.go

* Spotted by gilles@ running across sync'ed repos.

cleanup: Do not forget Indexes' root while doing colouring.

---

repository/repository.go
repository/state/state.go

* GetSubpartForBlob() is not the best place to test if a blob belongs to a deleted packfile. Indeed, there are some rare cases (concurrent backup and colouring cleanup phase) where we might have falsely flagged a packfile for deletion, only to roll it back later at sweep time. As such, it's valid to call GetSubpartForBlob(), since we still want people to be able to acces them.
* Rather, let's do this check in the BlobExists function, so that anyone trying to push new stuff will not see it as available.
* Note that this might endup doing a bit of duplication, if we imagine a scenario where we have a concurrent backup using blob X, but we marked X for deletion, later on if we have another backup that ends up with X BlobExists() will return false so we will commit the same blob to another …

cleanup: Fix for deleted Packfiles.

---

cmd/plakar/subcommands/create/create.go

the `on repository` syntax is invalid and it should be `at repository`.
the `on REPOSITORY` syntax isn't accurate. it should be `at REPOSITORY`.

fix usage in `create` subcommand

---

cmd/plakar/plakar.go

the code doesn't properly parse them if having it after. so reflects the reality and provides accurate usage string.
Fixes: #600

fix usage string: move `OPTIONS` before `at REPOSITORY`

---

cmd/plakar/subcommands/create/create.go

To reference a repository stored on s3, the syntax @REPOSITORY should be used. The syntax "s3://user:pass@domain" is not supported anymore.

create usage: fix ref to "plakar at s3://"

---

cmd/plakar/subcommands/agent/plakar-agent.1
cmd/plakar/subcommands/cat/plakar-cat.1
cmd/plakar/subcommands/check/plakar-check.1
cmd/plakar/subcommands/digest/plakar-digest.1
cmd/plakar/subcommands/exec/plakar-exec.1
cmd/plakar/subcommands/locate/plakar-locate.1
cmd/plakar/subcommands/ls/plakar-ls.1
cmd/plakar/subcommands/rm/plakar-rm.1

I used `mandoc -Tlint` to found and fixes some problems in man pages.
I did separated commits as some might not be not desirable (like "input text line longer than 80 bytes" or "snapshotID:path unification")

more manpages fixes

---

storage/backends/fs/fs.go

* Location() actually is the full "remote" line, so it might include the "fs://" URI scheme in it.
* Instead use Path() which resolves to the absolute path on the local filesystem.
* fixes 88c3126b7e
* Bug found and fix provided by sayoun@ ! Thx!

storage/fs: Use the right path when creation repo.

---

snapshot/importer/fs/fs.go
snapshot/importer/fs/walkdir.go
snapshot/importer/fs/walkdir_windows.go

* Before this, this is the record we produced when doing a backup like this:
./plakar backup -quiet /tmp/powerlog/
-> record /
-> record /tmp
-> record /tmp/powerlog/
That last record, with an appended slash doesn't fare well with our VFS layer and it breaks in all kind of ways.
* Let's sanitize the path once and for all when instantiating the fs importer so that the rootDir is always a path that we can process and we can respect the VFS layer contract.
* While here remove clean from the walkdir function, it's not the right place to do this.

importer/fs: Fix path cleaning.

---

api/api_snapshot.go

Provide a default extension when creating an archive, if the ?name is not given or if it does not include an extension.

API download: add extension to filename

---

repository/repository.go

when using `plakar -trace all` prefer hexadecimal output instead of raw string.

trace: use hexadecimal output for lockID in trace

---

packfile/packfile.go

* Passing a pointer to a slice makes binary.Read default to reflection rather than its fast path (which is static type matching), so remove the pointer indirection we don't need it.
* This is a 60% perf gain on GetPackfile.

packfile: Make deserialization faster.

---

cmd/plakar/subcommands/maintenance/maintenance.go

* This one is a bit expensive as we have to go through the actual repository and possibly open packfiles, but it's the only way (for now) to implement this properly

maintenance: Implement gc'ing of orphaned blobs.

---

snapshot/search.go

We need to keep track of both the current offset and the limit (the window size for the returned items).
spotted by jcastets@

search: fix pagination

---

snapshot/vfs/vfs.go

* if prefix is just / we can take the ScanAll shortcut
* otherwise, we can use WalkDir which is faster than a partial scan

vfs: speed up Files()

---

snapshot/backup.go
snapshot/store.go

Since we don't need to access the values stored in the indexes during backup, we can just store the serialized values instead of having to serialize/deserialize them all over the place.  (ever access to a node implicitly deserializes the values, and every write implicitly serializes the values again).
I can see a small speedup in backing up the plakar repository with vendored deps on my machine, haven't tested on a larger dataset yet.

less ser/deserialization during backup

---

api/api_repository.go

The endpoint /api/repository/locate-pathname was not working for the / folder.

Fix /api/repository/locate-pathname for root folder

---

cmd/plakar/subcommands/server/server.go

-allow-delete  will enable delete operations (and not disable them)

server: fix usage -allow-delete

---

snapshot/backup.go

it is useless but it falsifies accounting and causes a deadlock

do not reuse the maxConcurrency semaphore in importerJob, not only

---

caching/repository.go
cmd/plakar/plakar.go
repository/repository.go

which versions have touched a repo, while at it fix the plakar.go
swapping of cache when an agent client falls back to agentless

create per-repo client version cookies for the local machine to know

---

repository/repository.go

applying fix to the beta.6 empty state bug. to be removed when we
no longer see beta.6 hitting the version check

do a PutCurrentState() if this is the first run of a new version,

---

api/api_params_test.go
api/api_repository_test.go
api/api_snapshot_test.go
api/api_test.go
storage/storage_test.go
testing/backend.go

Now that we have proper checking in storage.New() we can finally call it what it is.

testing: rename the mock "fs" backend "mock"

---

cmd/plakar/plakar.go

The "server" command is executed early, so all subsequent tests for that value are actually useless.

Remove unreachable code intended for the "server" command

---

cmd/plakar/subcommands/ls/ls.go
snapshot/importer/fs/fs.go
snapshot/importer/fs/walkdir.go
snapshot/importer/fs/walkdir_windows.go
snapshot/vfs/entry.go
snapshot/vfs/vfs.go

This fixes two things actually:
* add more prefix directories to the backup so that both the user expectations and the backup navigation still works as expected
* fixes the behavior of `ls`; now it implicitly follows the symlinks inside the path.
Still a wip because Realpath() has to go away, we need an API that opens an entry following each symlinks along the path, but need to take care that Walkdir doesn't do that, otherwise we might loop indefinitely.

better handling of symlinks

---

api/api_snapshot.go

Move the `SnapshotPathParam()` block to after JWT cookie validity checking.
It avoids:
- parsing untrusted stuff before auth
- leaking if a particular snapshot is present in the repo or not

check jwt token before processing snapshot_path parameter

---

snapshot/synchronize.go
snapshot/vfs/entry.go
snapshot/vfs/vfs.go

Only works for entries returned by the VFS layer.

vfs: add entry.MAC()

---

cmd/plakar/subcommands/mount/mount_test.go

* On macos/darwin mount needs a kext loaded, this is too much of a high entry barrier for tests. Let's disable the mount test on darwin.

tests/mount: Repair darwin.

---

snapshot/importer/sftp/walkdir.go

We'd need to fetch the *remote* names, not resolving them locally.  The library we're using doesn't expose this, and it actually seems a bit hard generally speaking in SFTP, so for now better axe this code than providing a wrong info.
While here also remove the `go:build` directive and "modernize" a loop so LSP is happy!

importer/sftp: remove bogus username/groupname lookup

---

snapshot/check.go
snapshot/synchronize.go
snapshot/vfs/entry.go
snapshot/vfs/vfs.go

* The only accessor does nothing with it so no need for it to be private.
* We need it in the API so serialize it for json and omit it in msgpack to avoid recursing data structures!

entry: Make the MAC a public member.

---

snapshot/vfs/entry.go

I can't read: to return all the entries, a caller may use `n <= 0`, not necessarely `n == -1`.

vfs: fix vdir.ReadDir

---

compression/compression.go

* Lz4 maintains its own buffer pool to avoid putting too much pressure on the GC. Due to the way we do reads (individual GetBlob) we instantiate lz4 readers too frequently, therefore nullifying the the benefits of the internal buffer pool. To remediate this let's pool the lz4 readers instance ourselves.
* This gives us huge wins whenever we traverse the VFS:
(1) Maintenance:
- before:
real    23m55.998s
- after:
real    5m41.460s ===> -76%
(2) Check:
- before:
real    27m1.316s
- after:
real    3m35.044s ===> -86%
Other type of read heavy loads (restore/sync) should get a nice
performance boost too.
* The write (deflate) side doesn't benefit from pooling after testing, surely because they do not do buffer pooling for the write path.

compression: Implement a pool of lz4 readers.

---

cmd/plakar/subcommands/backup/backup.go
cmd/plakar/subcommands/backup/plakar-backup.1
cmd/plakar/subcommands/help/docs/plakar-backup.md

The syntax `plakar backup s3://...` is not valid anymore. To backup a remote, you should use the @ syntax and configure the remote in ~/.config/plakar/plakar.yml.

Fix plakar backup usage

---

api/api_snapshot.go
btree/btree.go
btree/cache.go
caching/lru/lru.go

This moves the btree LRU node cache to a standalone package and reuses it in the APIs as well.

api: introduce a snapshot LRU cache

---

btree/cache.go

Don't write the node back to the underlying store when it's evicted from the cache if it's not dirty.  It's a waste of I/O at best and a violation of some read-only stores at worst.

btree/cache: actually respect the dirty flag

---

cmd/plakar/subcommands/backup/backup.go

* When backing up we allow the user to ask for a check of the just created snapshot. Our check code now uses a cache, so let's specify one here before running it otherwise it crashes.
* We could also make the check code work without cache, but there are benefits (speed benefits) to running with a cache, even for a single snap check.
* Crash reported by niluje@

backup: Provide a check cache if check is specified.

---

repository/repositorywriter.go

* CommitTransaction pushes locally the deltaState ID because it expects it to be insert along the process. Make it true for DeleteRessource too.

state: Fix miantenance states.

---

snapshot/backup.go

if we're chunkify the file anyway, it doesn't cost us much to do the magic check instead of relying on the extension alone.
This fixes, among other things, `go.mod` being reported as an audio file.
Since snapshots are immutable, this doesn't retroactively fix the content-type association.

use mime.TypeByExtension only as last resort

---

api/api_repository.go

I mistakenly inverted the condition in 7a9ca6a9232.

Fix timeline

---

api/api_snapshot.go

niluje@ spotted that text/xml was still interpreted; so let's use the big hammer and serve all text/* stuff as text/plain to stay on the safe side.
The intent is to always show the content of the files in the UI, so we have to prevent the browser from trying to be 'smart'.

api: serve all text/* as text/plain

---

snapshot/backup.go

* Discussed with gilles@ and op@.
* This would lead to corruption in case of an aborted backup then doing it again. Because we would fetch the RT_OBJECT out of the VFS cache but then the first thing was putting it in the repository, therefore bypassing chunkify-cation of the object.

backup: Remove a erroneous PutBlob(OBJECT)

---

agent/agent.go
cli/entrypoint.go
cmd/plakar/subcommands/agent/agent.go
cmd/plakar/subcommands/agent/plakar-agent.1
cmd/plakar/subcommands/create/create.go
cmd/plakar/subcommands/help/docs/plakar-agent.md
cmd/plakar/subcommands/ptar/ptar.go
cmd/plakar/subcommands/server/server.go
cmd/plakar/subcommands/subcommands.go

* actually use the subcommands flags instead of special casing on the command name
* honour the AgentSupport flag
* change `agent -stop` into `agent stop` so that it can get properly registered
* make `agent stop` working across version bumps
`agent stop` is still issuing an `os.Exit`, this will be fixed afterwards, now the behaviour is the same as before the big cli overhaul.

assorted command line fixes

---

snapshot/importer/fs/fs.go
snapshot/importer/fs/walkdir.go
snapshot/importer/fs/walkdir_windows.go

reduce the number of goroutines (and headaches reading this code); split off the realpath thingy into its own function.

importer/fs: simplify walkdir_walker

---

caching/check.go
caching/packing.go

otherwise removal will fail on bogus constructed path

do not forget to set randomly generated id to the cache structure,

---

appcontext/appcontext.go
cmd/plakar/subcommands/backup/backup.go
scheduler/tasks.go

* For now, as we still tap into the CMD for agent's scheduler, we need to access the snapshot id created out of the backup. To do this, as things usually go in computer, provide another layer of indirection to fix this. Introduce a Do function that returns the needed information, and wraps that in the CMD Execute() func. The scheduler can directly use the Do func.
* While here remove the snapshotID from AppContext, this can't work like this.

cmd/backup: Provide the snapshot id created by the backup.

---

.github/workflows/codeql-analysis.yml

Potential fix for [https://github.com/PlakarKorp/plakar/security/code-scanning/70](https://github.com/PlakarKorp/plakar/security/code-scanning/70)
To fix the issue, we need to add a `permissions` block to the workflow. Since the workflow primarily involves analyzing code and does not require write access, we can set the permissions to `contents: read`. This ensures that the workflow has only the minimum required access to the repository contents.
The `permissions` block should be added at the root level of the workflow file, so it applies to all jobs in the workflow. Alternatively, it can be added specifically to the `analyze` job if other jobs in the workflow require different permissions.
_Suggested fixes powered by Copilot Autofix. Review carefully before merging._

Potential fix for code scanning alert no. 70: Workflow does not contain permissions

---

storage/backends/s3/s3.go

avoids to read all the data in memory; fixes a "high security issue" reported by CodeQL.

backends/s3: use a SectionReader for GetPackfileBlob

---

storage/backends/fs/buckets.go

CodeQL is "smart" enough to find out that the MAC passed to, for e.g., buckets.Put might come from the http server, and so it's user controlled.  Great.  Except it completely misses the point that the MAC gets serialized in hex format and so it's only made up of [A-Z].  The constructed path can't escape buckets.path in any way.

attempt to please CodeQL in the less horrible way possible

---

snapshot/importer/fs/fs.go

* Spotted during a perf regression tests, the lookup function kept showing in the flamegraphs, that's because we used the GID on the LookupId() function, which meant it failed all the time bypassing memoization.
* This whole gid branch was wrong anyway, using the wrong map too.

importer/fs: Use the correct gid table for memoization.

---

cmd/plakar/subcommands/agent/agent.go

otherwise we try to open the default repository when running the agent which we shouldn't.

subcommands/agent: fix registration flags

---

snapshot/exporter/exporter.go
snapshot/exporter/exporter_test.go
snapshot/exporter/fs/fs.go
snapshot/exporter/fs/fs_test.go
snapshot/exporter/ftp/ftp.go
snapshot/exporter/s3/s3.go
snapshot/exporter/s3/s3_test.go
snapshot/exporter/sftp/sftp.go
snapshot/exporter/stdio/stdio.go
snapshot/restore.go

the minio client will allocate excessive amounts of memory if the size of a file is unknown at push, ... however in Restore, we always know the size.

we know the size of the file we want to restore

---

ui/v2/ui.go

The token must now be provided in plakar_token to avoid conflicting with the token from api.plakar.io.

Fix UI URL

---

storage/storage.go

It makes more sense to return "null" when encryption and compression is disabled, rather than omitting the field.

api/repository/info: remove omitempty for encryption and compression

---

snapshot/importer/s3/s3.go

Records created with importer.NewScanRecord should not contain a trailing slash in the path, otherwise the backup layer fails to retrieve the parent directory.

s3 importer: fix directories creation

---

cmd/plakar/subcommands/backup/backup.go
cmd/plakar/subcommands/check/check.go
snapshot/check.go
snapshot/check_test.go

This tidies the check code a bit more.  It also includes #918 as a side-effect of the changes, depending on what we decide to do for the release this might wait a bit, or i can rebase it and fix the trivial conflict when #918 will get in.

continue the check refactoring

---

cmd/plakar/subcommands/info/repository.go

* the RepositorySecret is already present in the embedded structure.

info: Fix RPC.

---

cmd/plakar/subcommands/ptar/ptar.go
cmd/plakar/subcommands/sync/sync_test.go
location/location.go
snapshot/exporter/exporter.go
snapshot/exporter/fs/fs.go
snapshot/exporter/ftp/ftp.go
snapshot/exporter/s3/s3.go
snapshot/exporter/sftp/sftp.go
snapshot/exporter/stdio/stdio.go
snapshot/importer/fs/fs.go
snapshot/importer/ftp/ftp.go
snapshot/importer/importer.go
snapshot/importer/s3/s3.go
snapshot/importer/s3/s3_test.go
snapshot/importer/sftp/sftp.go
snapshot/importer/stdio/stdio.go
storage/backends/fs/fs.go
storage/backends/http/client.go
storage/backends/http/client_test.go
storage/backends/ptar/ptar.go
storage/backends/s3/s3.go
storage/backends/s3/s3_test.go
storage/backends/sftp/sftp.go
storage/backends/sqlite/sqlite.go
storage/storage.go
storage/storage_test.go

when hitting a storage backend

normalize locations to always carry <scheme>://<resource>

---

storage/backends/s3/s3.go

* This partially reverts 3935315a3, the changes to s3 broke s3 without prefixes, and we are too close to release to fix this up.

storage/s3: Fix prefix support.

---

cli/entrypoint.go
cmd/plakar/subcommands/agent/agent.go

Commands with the `BeforeRepositoryWithStorage` flag have their repository set up differently, but use the same exectution path as regular commands.

Use a common execution path for all commands with a repository.

---

cli/entrypoint.go

This way we can still ctrl-c our way out of the "repository passphrase:" prompt.

entrypoint: delay the signal trapping after subcommand.Parse

---

snapshot/importer/s3/s3.go

The functions Equal and EqualIgnoreSize of objects/fileinfo.go consider two fileinfo structs as different if the inode number is different.
Since the importer generates an inode per file, in the case a second import has one more file in the middle of the import, all the subsequent files will have a different inode and won't be considered as being cached.
As an alternative, we could also stop comparing the inodes in Equal and EqualIgnoreSize.

s3: do not store the inode

---

scheduler/config.go
scheduler/tasks.go

* Validate configuration (especially typed fields, like durations) at configure time rather than at execute.o
* It's hard to handle errors at runtime (what do you abort, what do you let run? etc) and can be surprising to the user. This validates all the fields at configure time and discards the config update if there are any problems.

tasks: Validate configuration at loading time.

---

api/api_params_test.go
api/api_repository_test.go
api/api_snapshot_test.go
api/api_test.go
appcontext/appcontext.go
go.mod
go.sum
main.go
scheduler/tasks.go
subcommands/agent/agent.go
subcommands/backup/backup_test.go
subcommands/help/help_test.go
subcommands/ptar/ptar.go
subcommands/sync/sync.go
testing/repository.go

kloset now takes the secrets in the Repository constructors instead of implicitly thru the kcontext.  To minimize the diff, move it in the appcontext for now.  Its lifetime may be shrunk in a follow-up.
kloset pr: https://github.com/PlakarKorp/kloset/pull/8

appcontext: move the secret in here

---

connectors/tar/importer/tar.go

unfortunately, hdr.Mode does not include the right bits for the types, so we have to fill them ourselves.

tar/importer: fix the entries type

---

subcommands/agent/agent.go

* This can lead to weird situation like having two agent processes, or failing to send commands (if you unset it after etc).
* It makes no sense anyway so prevent it.

agent: Disallow agent start with PLAKAR_AGENTLESS.

---

connectors/stdio/importer/stdio.go

we have to store the options in the contructor, to prevent a panic with nil pointer when calling Origin

fix stdio importer options hostname

---

connectors/fs/importer/fs.go
connectors/ftp/importer/ftp.go
connectors/s3/importer/s3.go
connectors/sftp/importer/walkdir.go
connectors/sftp/storage/sftp.go
connectors/sftp/storage/utils.go
connectors/stdio/importer/stdio.go

path is used to deal with UNIX-like paths, for e.g. URLs (stretching it a bit but still), while filepath is for the *local* operating system path format.
So, stick with path for remotes like (s)ftp and stdin, while the local fs has to use filepath.

fix some path vs filepath usage

---

main.go
subcommands/backup/backup.go

This is meant to help with windows, where a path like "C:\Users\Omar\" might be mistaken for a remote with "C" protocol.
What to exactly do in the command line when a user types the full path with the device included is still to solve.

for auto-generated paths, prefix "fs:"

---

plugins/plugin_loader.go
plugins/plugin_loader_windows.go
subcommands/agent/agent.go
subcommands/agent/daemonize.go
subcommands/agent/daemonize_windows.go

These are just faking some functions on windows, they'll need to be actually implemented in a follow up, but for now it make easier to add windows to the CI and stop breaking it all the time.

some quick fixes for windows

---

appcontext/appcontext.go

* The old kcontext did a full copy of the struct when in NewContextFrom, AppContext doesnt, so migrating the cookies/cookieDir meant that we would not get it set in the client context in agent mode.
* To fix it do a copy of cookiesDir / cookies, rather than copying the whole struct we have better control like this (discussed with eric@)
* reported-by eric@ fix discussed with eric@

appcontext: Fix NewAppcontextFrom.

---

subcommands/ptar/ptar.go

* Close the global scan cache we instantiate for the state.
* Close the snapshot which in turns closes the scan cache used by the backup routine.
* Found while working on cache cleanup for VFS.
* Note that in the case of the scan cache, closing it also means _removing_ the folder it was in. Without this we would clutter the .cache/plakar folder a bit.

ptar: Close cache and snapshots.

---

connectors/fs/importer/walkdir.go

Update the root directory only when we happen to scan a *file* that's equal to the scan dir, not just the scan dir itself.

fs/importer: fix reported root dir

---

plugins/plugin_loader.go
subcommands/pkg/create.go
subcommands/pkg/pkgimporter.go
subcommands/pkg/stdio.go

- now the manifest has to list all the files
- all files listed by the manifest must be at or below the manifest directory
- ensure that the executables are, in fact, executable

pkg create: add extra_files to the manifest; improve usage

---

subcommands/backup/backup.go
subcommands/backup/backup_test.go
subcommands/backup/plakar-backup.1
subcommands/help/docs/plakar-backup.md

Following discussion in issue #1191 (see https://github.com/PlakarKorp/plakar/issues/1191#issuecomment-3031262053), proposal to rename `excludes` option to `exclude-file` for `backup` subcommand.

backup subcommand: rename excludes option to exclude-file

---

README.md

* We moved away from ./cmd/plakar a while ago, it's now toplevel.

chore: Update install instruction in README.

---

main.go
subcommands/subcommands.go

This turns this
```
$ plakar
plakar: a subcommand must be provided
agent
agent reload
agent restart
agent start
agent stop
agent tasks configure
agent tasks start
agent tasks stop
archive
backup
cat
```
into
```
$ plakar
plakar: a subcommand must be provided
agent [reload | restart | start | stop | tasks]
archive
backup
cat
check
clone
create
destination
```
which i think it's more nice :)
In the future I'd also like to show the usage for the commands that don't take any parameter (i.e. `diff snap1[:path1] snap2[:path2]`), but that requires information that right now we don't have at this stage.

prettify command listing

---

subcommands/backup/backup.go
subcommands/backup/plakar-backup.1
subcommands/help/docs/plakar-backup.md

If you merge this PR, it will merge the code to `jcastets/plakar-backup-doc`.
This PR must be merged before https://github.com/PlakarKorp/plakar/pull/1225

Allow several tags in plakar backup

---

connectors/sftp/storage/utils.go

* Using ReadFromWithConcurrency, one saves us a temporary buffer, but also let's the pkg/sftp package pipeline the send giving way more throughtput.

sftp: Use ReadFromWithConcurrency for writes.

---

plakar.1
subcommands/help/docs/plakar-pkg-add.md
subcommands/help/docs/plakar-pkg-build.md
subcommands/help/docs/plakar-pkg-create.md
subcommands/help/docs/plakar-pkg-rm.md
subcommands/help/docs/plakar-pkg.md
subcommands/help/docs/plakar.md
subcommands/pkg/add.go
subcommands/pkg/pkg.go
subcommands/pkg/plakar-pkg-add.1
subcommands/pkg/plakar-pkg-build.1
subcommands/pkg/plakar-pkg-create.1
subcommands/pkg/plakar-pkg-manifest.yaml.5
subcommands/pkg/plakar-pkg-recipe.yaml.5
subcommands/pkg/plakar-pkg-rm.1
subcommands/pkg/plakar-pkg.1
subcommands/pkg/rm.go

This renames the pkg subcommands:
- `plakar pkg install` becomes `plakar pkg add`
- `plakar pkg uninstall` becomes `plakar pkg rm`
- `plakar pkg ls` becomes... `plakar pkg`
and adds some initial documentation for the subcommands and the file formats.

improve pkg naming; add initial docs

---

main.go
subcommands/create/create.go
subcommands/create/create_test.go

Get the passphrase from the env early and set it on the context.

Allow 'create' to use the passphrase from the config.

---

.github/workflows/go.yml

instead of using a global timeout for the action, let's add a (strict) limit on each test.  from the `go test` doc:
> If a test binary runs longer than duration d, panic.
> If d is 0, the timeout is disabled.
> The default is 10 minutes (10m).
one minute for each binary test should be way more than enough.  the advantage is that if we go over the limit, the test binary panics and we get a stacktrace, while if the action times out we don't have any info on what was happening.

ci: tweak timeout

---

scheduler/tasks.go
subcommands/agent/agent.go
utils/config.go

reload on config change, it can simply reopen config before reopening
repository for tasks, and reopen config when handling a new client

since configuration is now atomic, we no longer need to have an agent

---

main.go

* Go from nproc * 8 + 1 to nproc * 2 + 1. This made sense at the time cause we were heavily i/o bound. With our new fixed-size worker pipeline it's way less true but it consummes way too much memory.
* We have had quite a lot of report of people having OOM issues on memory constrained  machines etc.
* This doesn't affect performances much, see timings at the end of the commit message.
* This will also be needed by the new packing strategy which relies on having as many packfile opened as there are backup workers.
===============================
Before:
- Korpus to fs: k[ptr@c4v3 plakar]$ ./plakar -no-agent at www backup -quiet ~/dev/Korpus/ backup: created unsigned snapshot 6b7f410f of size 36 GB in 1m49.913605141s (wrote 29 GB)
- linux to s3: [ptr@c4v3 plakar]$ ./plakar -no-agent at …

main: Lower the default concurrency.

---

reporting/reporting.go

to make sure the reporter doesn't stop before all reports are processed.

use a counter on pending reports 

---

plugins/connect.go
plugins/connect_windows.go
plugins/manifest.go
plugins/plugin.go

this allows providing per type args in the manifest, with this it becomes possible to build importer/exporter/storage as a single executable with an argv dispatcher

pass parameters to plugin

---

plugins/connect.go
plugins/connect_windows.go
plugins/plugin.go

* Since the plugins are basically an infinite loop, when the parent process (plakar) dies we need to command.Kill the children, which is down through context cancellation.

plugins: When exec.Command pass down a context.

---

api/api_snapshot.go

EOF and non-EOF are handled the same, so...

simplify error handling

---

api/api_snapshot.go

before, empty files have always a white background:
after, correct:

api: fix auto preview for empty files

---

main.go
subcommands/agent/agent.go

To have the agent working on windows we need to implement a Service. For now, just implicitly disable the agent and unplug the subcommand.

windows: disable the agent by default

---

subcommands/help/docs/plakar-scheduler.md
subcommands/help/docs/plakar-server.md
subcommands/server/plakar-server.1
subcommands/server/server.go
subcommands/server/server_test.go

* be a bit more precise in the `-listen` description
* explain that without a host it listens on all addresses
* add CAVEATS to explain net.Listen behaviour
while here also return the error if `httpd.Server` fails (e.g. if the port is already bound) and sync the `-listen` default with the manpage.

server: improve the manpage

---

main.go
subcommands/agent/agent.go
subcommands/agent/agent_stop.go
subcommands/agent/osdep_unix.go
subcommands/agent/osdep_windows.go
subcommands/agent/plakar-agent.1

This is useful for updating from an older version.
Update the message in main when running against an older version.
Add documentation.

Reintroduce the agent stop command.

---

subcommands/agent/plakar-agent.1
subcommands/agent/start.go

noticed thanks to #1653, `-log` and `-foreground` were removed, but most of the logic is still there.  these changes were done in dbda028e9614e898353a619a444d472f47f0fad4, but I'm not sure about the direction: should we finish to kill the log and foreground support or readd them?
Here I'm readding them, and adjusting the documentation.  if we don't want them, given that now the agent is no longer that visible, is spawned automatically, it shuts down automatically, and we're also planning to remove it, i can amend this PR to just keep some of the manpage improvements and clean up the code.

plakar agent start: readd some flags, improve the manpage

---

ui/v2/ui.go

We updated plakar-ui and the dist/ folder now contains files starting with '_'.
By default, `go:embed` frontend/* does not include files starting with '.' or '_'. To import them, you need to use the syntax `go:embed all:frontend/*`.

api: embed files starting with _

---

subcommands/config/config.go

The `plakar store show $storename` command currently returns a successful exit code (0) even when the specified store configuration does not exist. This makes it difficult for scripts and automation tools to detect missing store configurations.
Modified the `dispatchSubcommand` function in `subcommands/config/config.go` to:
1. Show configurations for all existing stores
2. Report missing stores to stderr 
3. Return an error code if any requested stores don't exist
This maintains backward compatibility for showing multiple stores while ensuring proper error reporting.
- **File:** `subcommands/config/config.go`
- **Function:** `dispatchSubcommand` (case "show")
- **Change:** Added error tracking to show existing stores while failing if any are missing
**Before:**
```bash
$ plakar store show …
```

Fix `plakar store show` to return error when store doesn't exist
